- README.md
- package-lock.json
- package.json
- src/lib/elements/Meter/Meter.scss
- src/lib/elements/Meter/Meter.test.tsx
- src/lib/elements/Meter/Meter.tsx
- src/lib/elements/Meter/index.ts
- src/lib/elements/index.ts
- src/lib/index.ts
- tsconfig.json
- vite.config.ts
- add Meter component
There's an issue with dependencies in maas-ui that results in an error about multiple react versions when following the QA steps above. This will be addressed separately.
https://github.com/facebook/react/issues/13991#issuecomment-435135293
> feat: add Meter component

- .storybook/main.js
- GUIDELINES.md
- stories/Readme.stories.mdx
- docs: display GUIDELINES.md in storybook as a landing page
> docs: display GUIDELINES.md in storybook

- .storybook/preview.scss
- package-lock.json
- package.json
- src/lib/elements/ExternalLink/ExternalLink.stories.tsx
- src/lib/elements/ExternalLink/ExternalLink.test.tsx
- src/lib/elements/ExternalLink/ExternalLink.tsx
- src/lib/elements/ExternalLink/index.ts
- vite.config.ts
- add `ExternalLink` component
In case you happen to have errors about different react versions/breaking rules of hooks you may need to run `yarn link ../maas-ui/node_modules/react` in the `maas-react-components` local repository to make sure it resolves to the correct version.
https://react.dev/warnings/invalid-hook-call-warning#duplicate-react
> feat: add ExternalLink component

- .storybook/manager.ts
- .storybook/theme.ts
- src/lib/components/NestedFormGroup/NestedFormGroup.stories.tsx
- Disable source code in controlled example of NestedFormGroup
- Move storybook theme to own file
Fixes:
> docs: disable controlled example source code

- .storybook/DocumentationTemplate.mdx
- stories/Readme.stories.mdx
-  Remove default storybook styles so that vanilla framework styles are applied by default
> docs: remove default storybook styles

- src/lib/sections/Navigation/Navigation.scss
- Set cursor to pointer when hovering active nav items
Fixes [MAASENG-2405](https://warthogs.atlassian.net/browse/MAASENG-2405)
[MAASENG-2405]: https://warthogs.atlassian.net/browse/MAASENG-2405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(nav): cursor is pointer for active items MAASENG-2405

- src/lib/sections/Navigation/Navigation.scss
- Increased specificity of `cursor: pointer` rule
This was done since there were some conflicts with base vanilla styles, meaning that this did not work in MAAS UI or Site Manager.
> fix: increase specificity of pointer cursor rule

- .storybook/DocumentationTemplate.mdx
- .storybook/preview.scss
- src/lib/sections/MainToolbar/MainToolbar.scss
- src/lib/sections/MainToolbar/MainToolbar.stories.tsx
- src/lib/sections/MainToolbar/MainToolbar.test.tsx
- src/lib/sections/MainToolbar/MainToolbar.tsx
- src/lib/sections/MainToolbar/index.ts
- src/lib/sections/index.ts
- src/types.ts
- feat: add MainToolbar component
It automatically adjusts its layout based on available space. `MainToolbar.Title` and `MainToolbar.Controls` are wrapped to separate rows using CSS flexbox.
`MainToolbar.Controls` switches to a stacked layout when it overflows the container. This couldn't be achieved easily using pure CSS. For that reason a non-stacked hidden clone of `MainToolbar.Controls` is always displayed in the background for comparison and measured using `ResizeObserver`.
Designs: https://zpl.io/z8JleKl
Repeat in a few different browsers:
Fixes: [MAASENG-2438](https://warthogs.atlassian.net/browse/MAASENG-2438)
[MAASENG-2438]: https://warthogs.atlassian.net/browse/MAASENG-2438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add MainToolbar component

- src/lib/sections/MainToolbar/MainToolbar.scss
- fix: main toolbar styles specificity
This increases the specificity of styles by wrapping them in parent class (.main-toolbar) which fixes styling of certain nested elements. This specifically affects reduction of the margin of all direct descendants for consistent spacing.
Fixes:
> fix: main toolbar styles specificity

- src/lib/sections/ContentSection/ContentSection.tsx
- Replaced `div` with `header` in `ContentSection.Header`
- Replaced `div` with `footer` in `ContentSection.Footer`
> fix: use semantic elements for ContentSection Header and Footer

- src/lib/components/FadeInDown/FadeInDown.scss
- src/lib/components/FadeInDown/FadeInDown.stories.tsx
- src/lib/components/FadeInDown/FadeInDown.test.tsx
- src/lib/components/FadeInDown/FadeInDown.tsx
- src/lib/components/FadeInDown/index.ts
- src/lib/components/MultiSelect/MultiSelect.scss
- src/lib/components/MultiSelect/MultiSelect.stories.tsx
- src/lib/components/MultiSelect/MultiSelect.test.tsx
- src/lib/components/MultiSelect/MultiSelect.tsx
- src/lib/components/MultiSelect/index.ts
- src/lib/components/NestedFormGroup/NestedFormGroup.scss
- src/lib/components/NestedFormGroup/NestedFormGroup.tsx
- src/lib/components/index.ts
This adds a multi select component and introduces an internal FadeInDown component for handling fade in transitions. This is experimental and should be used internally only for now.
- feat: add multi select component
Fixes: MAASENG-2534
> feat: add multi select component

- src/lib/components/MultiSelect/MultiSelect.stories.tsx
- src/lib/components/MultiSelect/MultiSelect.test.tsx
- src/lib/components/MultiSelect/MultiSelect.tsx
- Updated `MultiSelectItem` to be `{ label: string; value: string | number }`
Fixes [MAASENG-2613](https://warthogs.atlassian.net/browse/MAASENG-2613)
[MAASENG-2613]: https://warthogs.atlassian.net/browse/MAASENG-2613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(MultiSelect): update MultiSelectItem type to be label+value object MAASENG-2613

- src/lib/components/MultiSelect/MultiSelect.tsx
- Filter items for `selectedElements` to intersection between `items` and `selectedItems`
This is so that multiple `MultiSelect`s can use a shared state, which makes [MAASENG-2541](https://warthogs.atlassian.net/browse/MAASENG-2565) much easier
[MAASENG-2541]: https://warthogs.atlassian.net/browse/MAASENG-2541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(MultiSelect): only show selected items that also exist in items array

- package-lock.json
- package.json
- src/lib/components/FadeInDown/FadeInDown.scss
- src/lib/components/MultiSelect/MultiSelect.scss
- src/lib/components/MultiSelect/MultiSelect.stories.tsx
- src/lib/components/MultiSelect/MultiSelect.test.tsx
- src/lib/components/MultiSelect/MultiSelect.tsx
- src/lib/sections/Navigation/CollapseToggle/CollapseToggle.test.tsx
- feat: multiselect search and condensed variants
- introduce separate variants: `condensed` and `search`
- sort groups items alphabetically
- update react-components
- fix failing test
Does not include pinning previously selected items to the top, will be implemented separately: https://warthogs.atlassian.net/browse/MAASENG-2625
Fixes: MAASENG-2589
> feat: multiselect search and condensed variants

- .storybook/main.js
- package-lock.json
- package.json
- src/lib/utils/formatBytes/formatBytes.stories.tsx
- src/lib/utils/formatBytes/formatBytes.test.ts
- src/lib/utils/formatBytes/formatBytes.ts
- src/lib/utils/formatBytes/index.ts
- src/lib/utils/index.ts
- src/utils.tsx
- feat: add `formatBytes` util
- add utils section to storybook along with utility for easy display of future utils in the docs
- add `storybook-addon-pseudo-states`
https://warthogs.atlassian.net/browse/MAASENG-2651
> feat: add formatBytes util

- src/lib/components/MultiSelect/MultiSelect.scss
- src/lib/components/MultiSelect/MultiSelect.tsx
- fix: add multiselect overlow ellipsis
> fix: multiselect overlow

- src/lib/components/MultiSelect/MultiSelect.scss
- src/lib/components/MultiSelect/MultiSelect.stories.tsx
- src/lib/components/MultiSelect/MultiSelect.test.tsx
- src/lib/components/MultiSelect/MultiSelect.tsx
- feat(multiselect): display previously selected items at the top
- fix: use correct max height when multiple groups are used
- docs: update examples to include alphanumeric labels
Fixes: https://warthogs.atlassian.net/browse/MAASENG-2625
> feat(multiselect): display previously selected at the top

- src/lib/components/Pagination/Pagination.test.tsx
- src/lib/components/Pagination/Pagination.tsx
- allow custom label
- allow custom className
- make pagination props optional
Fixes:
> feat(pagination): allow custom label

- src/lib/sections/MainToolbar/MainToolbar.scss
- Removed absolute positioning for search icon to prevent overlap
Fixes: [MAASENG-2898](https://warthogs.atlassian.net/browse/MAASENG-2898)
[MAASENG-2898]: https://warthogs.atlassian.net/browse/MAASENG-2898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(style): remove absolute icon positioning to prevent overlapping

- package-lock.json
- package.json
- src/constants.ts
- src/lib/components/DynamicTable/DynamicTable.scss
- src/lib/components/DynamicTable/DynamicTable.stories.tsx
- src/lib/components/DynamicTable/DynamicTable.test.tsx
- src/lib/components/DynamicTable/DynamicTable.tsx
- src/lib/components/DynamicTable/index.ts
- src/lib/components/index.ts
- Upstreamed DynamicTable from MSM
Fixes [MAASENG-2987](https://warthogs.atlassian.net/browse/MAASENG-2987)
[MAASENG-2987]: https://warthogs.atlassian.net/browse/MAASENG-2987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: dynamic table MAASENG-2987

- src/lib/components/DynamicTable/DynamicTable.scss
- src/lib/components/DynamicTable/DynamicTable.stories.tsx
- src/lib/components/DynamicTable/DynamicTable.test.tsx
- src/lib/components/DynamicTable/DynamicTable.tsx
- src/lib/components/TableCaption/TableCaption.stories.tsx
- feat: allow multiple DynamicTable per page MAASENG-3091
- add `variant` prop
- use React's Context API for managing the variant prop.
_Note: Variant prop is required deliberately so that we're careful when updating existing implementations and carefully chose which variant should be used._
Context API provides a way to pass data through the component tree without having to pass props down manually at every level. This also allows to use this prop in all child components and make sure it's consistent and cannot be overwritten.
Fixes: https://warthogs.atlassian.net/browse/MAASENG-3091 https://github.com/canonical/maas-react-components/issues/128
> feat: allow multiple DynamicTable per page MAASENG-3091

- src/lib/components/GenericTable/ColumnHeader/ColumnHeader.scss
- src/lib/components/GenericTable/ColumnHeader/ColumnHeader.tsx
- src/lib/components/GenericTable/ColumnHeader/index.ts
- src/lib/components/GenericTable/GenericTable.scss
- src/lib/components/GenericTable/GenericTable.stories.tsx
- src/lib/components/GenericTable/GenericTable.test.tsx
- src/lib/components/GenericTable/GenericTable.tsx
- src/lib/components/GenericTable/GroupRowActions/GroupRowActions.test.tsx
- src/lib/components/GenericTable/GroupRowActions/GroupRowActions.tsx
- src/lib/components/GenericTable/GroupRowActions/index.ts
- src/lib/components/GenericTable/PaginationBar/ControlsBar/ControlsBar.tsx
- src/lib/components/GenericTable/PaginationBar/ControlsBar/index.ts
- src/lib/components/GenericTable/PaginationBar/PaginationBar.tsx
- src/lib/components/GenericTable/PaginationBar/index.ts
- src/lib/components/GenericTable/SortingIndicator/SortingIndicator.tsx
- src/lib/components/GenericTable/SortingIndicator/index.ts
- src/lib/components/GenericTable/TableCheckbox/TableCheckbox.test.tsx
- src/lib/components/GenericTable/TableCheckbox/TableCheckbox.tsx
- src/lib/components/GenericTable/TableCheckbox/index.ts
- src/lib/components/GenericTable/index.ts
- Upstreamed GenericTable with accompanying subcomponents
- Created stories for GenericTable
- Added more specific styling formerly handled by maas-ui
- Made  TableCheckbox.All visible for ungrouped selectable tables
- Forced pagination to flex row alignement
- Added the list of page size choices as a pagination prop
Resolves: 
[MAASENG-4794](https://warthogs.atlassian.net/browse/MAASENG-4794)
[MAASENG-4794]: https://warthogs.atlassian.net/browse/MAASENG-4794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Upstream GenericTable MAASENG-4794

- src/lib/components/GenericTable/GenericTable.test.tsx
- src/lib/components/GenericTable/GenericTable.tsx
- Added destructured props to the GenericTableProps to accept all DetailedHTMLProps for HTMLDivElement (e.g. aria props)
- Update height adjustment so that the full-height styling is only applied if the variant is set to full-height AND the height of the table overflows its container
- Updated full-height test to match the new feature
> feat(components): GenericTable enhancement

- src/lib/components/GenericTable/GenericTable.scss
- src/lib/components/GenericTable/GenericTable.stories.tsx
- src/lib/components/GenericTable/GenericTable.tsx
- Added onClick to the entire group row to toggle expansion
- Added optional chevron to display group expansion state
- Fixed paginated group expansion bug
Fixes: 
[MAASENG-5326](https://warthogs.atlassian.net/browse/MAASENG-5326)
You can use the following changes to the GroupedSelectable story to test the changes.
```ts
export const GroupedSelectable: Story = {
name: "Grouped (Selectable)",
render: (args) => {
const [rowSelection, setRowSelection] = useState<RowSelectionState>({});
const [currentPage, setCurrentPage] = useState(1);
const [itemsPerPage, setItemsPerPage] = useState(5);
const startIndex = (currentPage - 1) * itemsPerPage;
const data = generateMachinesData(20);
data.sort((a, b) => {
return a.status > b.status ? 1 : a.status < b.status ? -1 : 0;
});
const paginatedData = …
```
> fix(components): Fix paginated expansion bug MAASENG-5326
