canonical/maas-react-components

README.md
package.json
tsconfig.json

build: setup local autolink

---

.github/workflows/release.yml
.releaserc
package-lock.json
package.json

Set up a GitHub Actions workflow to automate releases using Semantic Release.
- Add a new `.github/workflows/release.yml` file to define the release workflow, triggered on pushes to the `main` branch
- Add a new `.releaserc` file to configure Semantic Release plugins and settings
- Add Semantic Release related scripts to `package.json` and update devDependencies
- Enforce type checking when running `lint` script
The new release workflow will automatically create a GitHub release, update the `CHANGELOG.md`, and publish the package to npm when changes are pushed to the `main` branch.
- run `npm run semantic-release-dry-run` and ensure there are no errors thrown

chore: setup semantic release

---

.github/workflows/CI.yml
.husky/pre-commit
.releaserc

- Ci update test rules and release configuration
- Removed git commit (it's not necessary for the release and makes things unnecessarily complicated)
- Optimised CI workflow by using matrix
- Added husky pre-commit steps (lint & test)

ci: update test rules & release configuration

---

src/lib/elements/Meter/Meter.stories.tsx

- docs: add Meter to storybook

docs: add Meter to storybook

---

.github/workflows/release.yml
.releaserc

- fix: semantic release publish

fix: semantic release publish

---

GUIDELINES.md

- docs: legacy components
Fixes:

docs: legacy components

---

.husky/pre-commit
package-lock.json
package.json
plopfile.js
templates/component.test.tsx.hbs
templates/component.tsx.hbs
templates/index.ts.hbs

This Pull Request adds a new `create-component` script to streamline the component creation process. 
- Added the plopfile.js configuration for component generation along with required templates
- Set husky to run lint:fix on pre-commit
Fixes: https://warthogs.atlassian.net/browse/MAASENG-2208

feat: add component scaffolding tooling with plop

---

src/lib/components/NestedFormGroup/NestedFormGroup.stories.tsx
src/lib/elements/ExternalLink/ExternalLink.stories.tsx

-  update component categories (ExternalLink moved to elements)
-  add link to NestedFormGroup proposal
Fixes:

docs: update component categories

---

GUIDELINES.md

- Update "Components" categories documentation

docs: update components categories

---

README.md

- docs: create-component script

docs: create-component script

---

.github/workflows/CI.yml
.github/workflows/pr-lint.yml

- ci: add pr lint action
Fixes:

ci: add pr lint

---

src/lib/sections/Navigation/MenuButton/MenuButton.tsx

- Added focus removal logic from Site Manager to Menu Button
Fixes:

fix: remove focus from menu button after click

---

.github/pull_request_template.md

- Added "Ensure component renders correctly across all breakpoints" to PR template file

chore: add breakpoint qa step to pr template

---

src/lib/components/NestedFormGroup/NestedFormGroup.scss
src/lib/index.ts
src/lib/sections/FormSection/FormSection.scss
src/lib/sections/FormSection/FormSection.stories.tsx
src/lib/sections/FormSection/FormSection.test.tsx
src/lib/sections/FormSection/FormSection.tsx
src/lib/sections/FormSection/index.ts
src/lib/sections/InputGroup/InputGroup.scss
src/lib/sections/InputGroup/InputGroup.stories.tsx
src/lib/sections/InputGroup/InputGroup.test.tsx
src/lib/sections/InputGroup/InputGroup.tsx
src/lib/sections/InputGroup/index.ts
src/lib/sections/index.ts

- feat: add input group and form section components
Fixes: https://warthogs.atlassian.net/browse/MAASENG-2426
https://www.figma.com/file/SwzF1ts1o8gASc3cBfIOMw/Settings-consistency?type=design&node-id=14-15078&mode=design&t=Uxu1cIVAqkTXulYy-0

feat: add input group and form section components

---

.github/pull_request_template.md
plopfile.js
templates/component.stories.tsx.hbs

- feat: generate stories for new components
Fixes:

feat: generate stories for new components

---

src/lib/components/Pagination/Pagination.scss
src/lib/components/Pagination/Pagination.stories.tsx
src/lib/components/Pagination/Pagination.test.tsx
src/lib/components/Pagination/Pagination.tsx
src/lib/components/Pagination/PaginationContainer.test.tsx
src/lib/components/Pagination/index.ts
src/lib/components/index.ts

- Created Pagination component
- Created PaginationContainer wrapper component, containing logic for event handlers
- Added styles
- Created component story for Pagination
Fixes [MAASENG-2429](https://warthogs.atlassian.net/browse/MAASENG-2429)
[MAASENG-2429]: https://warthogs.atlassian.net/browse/MAASENG-2429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Create Pagination component MAASENG-2429

---

src/lib/sections/ContentSection/ContentSection.scss
src/lib/sections/ContentSection/ContentSection.stories.tsx
src/lib/sections/ContentSection/ContentSection.test.tsx
src/lib/sections/ContentSection/ContentSection.tsx
src/lib/sections/ContentSection/index.ts
src/lib/sections/Navigation/Link/Link.tsx
src/lib/sections/Navigation/Logo/Logo.tsx
src/lib/sections/Navigation/types.ts
src/lib/sections/index.ts
src/types.ts

- feat: add content section component
- move AsProp to global types
Fixes:

feat: add content section component

---

src/lib/sections/ContentSection/ContentSection.scss
src/lib/sections/ContentSection/ContentSection.tsx

- fix: content section padding
- set footer alignment to right as per design

fix: content section padding

---

.stylelintrc.json
package-lock.json
package.json
src/lib/components/NestedFormGroup/NestedFormGroup.scss
src/lib/sections/ContentSection/ContentSection.scss
src/lib/sections/ContentSection/ContentSection.stories.tsx
src/lib/sections/ContentSection/ContentSection.tsx
src/lib/sections/MainToolbar/MainToolbar.scss
src/lib/sections/Navigation/Navigation.scss

- feat: add content section variant
Note: https://github.com/canonical/maas-react-components/pull/48 needs to be merged first
https://warthogs.atlassian.net/browse/MAASENG-2432

feat: add content section variant

---

src/lib/sections/ContentSection/ContentSection.scss
src/lib/sections/ContentSection/ContentSection.stories.tsx
src/lib/sections/ContentSection/ContentSection.tsx
src/lib/sections/MainToolbar/MainToolbar.scss
src/lib/sections/Navigation/Navigation.stories.tsx

- feat: content section with toolbar
- make sure spacing is consistent across layout elements
Fixes:

feat: content section with toolbar

---

src/lib/sections/ContentSection/ContentSection.stories.tsx

- Added a ContentSection example with a footer nested within CS.Content

docs: add nested footer example

---

.stylelintrc.json
src/lib/components/Stepper/Stepper.scss
src/lib/components/Stepper/Stepper.stories.tsx
src/lib/components/Stepper/Stepper.test.tsx
src/lib/components/Stepper/Stepper.tsx
src/lib/components/Stepper/index.ts
src/lib/components/index.ts

- feat: add stepper MAASENG-2535
- disable scss/at-extend-no-missing-placeholder
Fixes: [MAASENG-2535](https://warthogs.atlassian.net/browse/MAASENG-2535)
[MAASENG-2535]: https://warthogs.atlassian.net/browse/MAASENG-2535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add stepper MAASENG-2535

---

package-lock.json
package.json
src/lib/components/FileUpload/FileUpload.scss
src/lib/components/FileUpload/FileUpload.stories.tsx
src/lib/components/FileUpload/FileUpload.test.tsx
src/lib/components/FileUpload/FileUpload.tsx
src/lib/components/FileUpload/index.ts
src/lib/components/Stepper/Stepper.scss
src/lib/components/index.ts

- feat: add file upload component

feat: add file upload component

---

src/lib/index.ts

- fix: add utils export
Fixes:

fix: add utils export

---

src/lib/components/FileUpload/FileUpload.tsx

- Added `type="button"` to button component of FileUpload

fix(FileUpload): add "type=button" to file upload button

---

src/lib/utils/formatBytes/formatBytes.stories.tsx
src/utils.tsx

- docs: add title to storybok util
- remove legacy status
Fixes:

docs: add title to storybok util

---

Dockerfile
konf/site.yaml

ci: enable pr demos

---

src/lib/components/FileUpload/FileUpload.scss
src/lib/components/FileUpload/FileUpload.stories.tsx
src/lib/components/FileUpload/FileUpload.test.tsx
src/lib/components/FileUpload/FileUpload.tsx

- Display accepted files beneath dropzone
- Display rejected files (and reasons) beneath dropzone
- Hide drop zone when max file limit is reached
- Create `FileUploadContainer`
- Fix border CSS
- Add error state for drop zone
- Add label and help props
- Add button to remove files (accepted or rejected)
Design reference: https://zpl.io/YPwBPrL
Fixes [MAASENG-2588](https://warthogs.atlassian.net/browse/MAASENG-2588)
[MAASENG-2588]: https://warthogs.atlassian.net/browse/MAASENG-2588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FileUpload): verify file upload component MAASENG-2588

---

.storybook/DocumentationTemplate.mdx

- docs: fix primary story controls
Fixes:

docs: fix primary story controls

---

src/lib/components/MultiSelect/MultiSelect.test.tsx
src/lib/components/MultiSelect/MultiSelect.tsx

- fix: sort multiselect input label values
Fixes:

fix: sort multiselect input label values

---

renovate.json

This PR configures renovate to group updates into categories, reducing the number of pull requests and making updates more manageable.
- chore: add package rules to renovate.json
Fixes:

chore: add package rules to renovate.json

---

src/lib/elements/Placeholder/Placeholder.scss
src/lib/elements/Placeholder/Placeholder.stories.tsx
src/lib/elements/Placeholder/Placeholder.test.tsx
src/lib/elements/Placeholder/Placeholder.tsx
src/lib/elements/Placeholder/index.ts
src/lib/elements/index.ts

- Added `Placeholder` component from MSM
*this is optional since `yarn link` can be janky and may not work correctly

feat: add table placeholder

---

templates/component.stories.tsx.hbs

- chore: add StoryObj to plop template

chore: add StoryObj to plop template

---

src/lib/components/DynamicTable/DynamicTable.scss
src/lib/components/TableCaption/TableCaption.stories.tsx
src/lib/components/TableCaption/TableCaption.test.tsx
src/lib/components/TableCaption/TableCaption.tsx
src/lib/components/TableCaption/index.ts
src/lib/components/index.ts

- Upstreamed `TableCaption` from MSM
Fixes [MAASENG-2987](https://warthogs.atlassian.net/browse/MAASENG-2987)
[MAASENG-2987]: https://warthogs.atlassian.net/browse/MAASENG-2987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: upstream TableCaption from MSM MAASENG-2987

---

.storybook/main.js
package-lock.json
package.json

- fix: react-components scss
- update vanilla framework
- use storybook story v7 format
Fixes:

fix: react-components scss

---

package-lock.json
package.json
src/lib/components/Pagination/Pagination.test.tsx

- chore: upgrade react-components 0.5.1
Fixes:

chore: upgrade react-components 0.5.1

---

package.json

- Ran `npm pkg fix` to fix errors with package.json file
This is mostly to test that our updated access token is working for semantic release

fix: autofix package.json with 'npm pkg fix'

---

src/lib/components/GenericTable/GenericTable.stories.tsx
src/lib/components/GenericTable/GenericTable.test.tsx
src/lib/components/GenericTable/GenericTable.tsx
src/lib/components/GenericTable/GroupRowActions/GroupRowActions.test.tsx
src/lib/components/GenericTable/GroupRowActions/GroupRowActions.tsx
src/lib/components/GenericTable/GroupRowActions/index.ts
src/lib/components/GenericTable/index.ts
src/lib/components/index.ts

- Changed GenericTable and GroupRowActions to named exports
- Exported both from the lib

fix: Converted new components to named exports

---

src/lib/components/QueryInput/QueryInput.scss
src/lib/components/QueryInput/QueryInput.stories.tsx
src/lib/components/QueryInput/QueryInput.test.tsx
src/lib/components/QueryInput/QueryInput.tsx
src/lib/components/QueryInput/index.ts
src/lib/components/index.ts

- Created QueryInput component, stories and tests
Resolves: 
[MAASENG-5149](https://warthogs.atlassian.net/browse/MAASENG-5149)
[MAASENG-5148]: https://warthogs.atlassian.net/browse/MAASENG-5148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAASENG-5149]: https://warthogs.atlassian.net/browse/MAASENG-5149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Create QueryInput component MAASENG-5149

---

.husky/commit-msg
.husky/pre-commit
commitlint.config.js
package-lock.json
package.json

- removed husky
- removed pre-commit hooks

chore: remove husky and pre-commit hooks
